# Generated by Django 5.2.8 on 2025-11-27 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='application_method',
        ),
        migrations.RemoveField(
            model_name='service',
            name='fee',
        ),
        migrations.AddField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline'), ('Both', 'Both')], default='Offline', max_length=50),
        ),
        migrations.AddField(
            model_name='service',
            name='validity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
