# Generated by Django 5.2.3 on 2025-11-28 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_remove_service_application_method_remove_service_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline'), ('Offline/Online', 'Offline/Online')], default='Offline', max_length=50),
        ),
    ]
