# Generated by Django 5.2.8 on 2025-11-30 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service_is_popular_alter_service_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicephoto',
            name='photo_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
