# Generated by Django 5.2.8 on 2025-12-02 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_savedservice'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='savedservice',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='savedservice',
            name='service',
        ),
        migrations.RemoveField(
            model_name='savedservice',
            name='user',
        ),
        migrations.DeleteModel(
            name='ApplicationStatus',
        ),
        migrations.DeleteModel(
            name='SavedService',
        ),
    ]
